// Code generated by "stringer -type=PromptType"; DO NOT EDIT.

package gitgen

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PromptCommitMessage-0]
	_ = x[PromptCodeReview-1]
}

const _PromptType_name = "PromptCommitMessagePromptCodeReview"

var _PromptType_index = [...]uint8{0, 19, 35}

func (i PromptType) String() string {
	if i < 0 || i >= PromptType(len(_PromptType_index)-1) {
		return "PromptType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PromptType_name[_PromptType_index[i]:_PromptType_index[i+1]]
}
